### ISSUE TITLE
Republish Microsite to fix Installing Page

### ISSUE THREAD

**Issue by jrduncans** [SystemFw/dynosaur#15]
The installing page at https://systemfw.org/dynosaur/#/installing shows `libraryDependencies += "org.systemfw" %% "dynosaur" % "0.2.0"` but the source shows the corrected `dynosaur-core` (and would presumably also update to show the current 0.3.0 version).

**Comment by SystemFw** [comment]
Thanks, not sure why it broke, I've republished it now
