### ISSUE TITLE
Missing leading `{` when rendering a Map

### ISSUE THREAD

**Issue by theon** [SystemFw/dynosaur#34]
Hi,

I noticed when calling `DynamoValue.toString` the resulting JSON is missing the leading `{` resulting in invalid JSON

See this test case for an example: https://github.com/SystemFw/dynosaur/blame/main/modules/core/shared/src/test/scala/DynamoValueSuite.scala#L169

**Comment by SystemFw** [comment]
Hey, thanks for reporting this! I'll have a look later today

**Comment by SystemFw** [comment]
So, I refreshed my memory, and this is by design, it's consistent with how the various AttributeValue types are rendered in https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_AttributeValue.html
